### PR TITLE
Python 3.9 upgrade

### PR DESCRIPTION
**Pull request by terovirtanen**
Pip installation for dependencies failed on DevOps due outdated dependencies. 
Pip installation were success after upgrade all dependency packages to the newer versions.

[PT-1665](https://helsinkisolutionoffice.atlassian.net/browse/PT-1665)

[PT-1665]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**kultus-api branch is deployed to platta: https://kultus-api-pr309.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-api branch is deployed to platta: https://kultus-api-pr309.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-api branch is deployed to platta: https://kultus-api-pr309.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-api branch is deployed to platta: https://kultus-api-pr309.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-api branch is deployed to platta: https://kultus-api-pr309.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-api branch is deployed to platta: https://kultus-api-pr309.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-api branch is deployed to platta: https://kultus-api-pr309.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-api branch is deployed to platta: https://kultus-api-pr309.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-api branch is deployed to platta: https://kultus-api-pr309.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-api branch is deployed to platta: https://kultus-api-pr309.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-api branch is deployed to platta: https://kultus-api-pr309.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by karisal-anders** [comment]
The pipeline is still requiring "Coding style" and "Tests" to be reported:
image

Quite a lot of the SonarCloud Code Analysis seems to do with the snapshots, as they are automatically generated perhaps they could be excluded i.e. all /snapshots/ directories from the SonarCloud Code Analysis? Not necessary to do in this PR IMHO, but an idea how to make things better.

**Review by nikomakela — APPROVED** [review]
The unit tests passes and I also did some manual testing, but I'm a bit scared of these: 

```
django-filter==23.1
    # via -r requirements.in
django-graphql-jwt==0.3.4
    # via -r requirements.in
django-helusers==0.8.1
    # via -r requirements.in
```

There were also 4 migrations included, which might make the possible rollbacking a bit harder:

```
Running migrations:
  Applying axes.0007_alter_accessattempt_unique_together... OK
  Applying axes.0008_accessfailurelog... OK
  Applying mailer.0005_id_bigautofield... OK
  Applying social_django.0011_alter_id_fields... OK
```

Anyway, we do have our testing environments, so let's try. I don't think we have any alternatives 😄 

@karisal-anders could review the changes also!

**Comment by karisal-anders** [comment]
```bash
kultus-backend |        git config --global --add safe.directory /app
kultus-backend | Traceback (most recent call last):
kultus-backend |   File "/app/./manage.py", line 21, in <module>
kultus-backend |     main()
kultus-backend |   File "/app/./manage.py", line 17, in main
kultus-backend |     execute_from_command_line(sys.argv)
kultus-backend |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
kultus-backend |     utility.execute()
kultus-backend |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
kultus-backend |     django.setup()
kultus-backend |   File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
kultus-backend |     apps.populate(settings.INSTALLED_APPS)
kultus-backend |   File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
kultus-backend |     app_config.ready()
kultus-backend |   File "/app/organisations/apps.py", line 8, in ready
kultus-backend |     import organisations.notifications  # noqa
kultus-backend |   File "/app/organisations/notifications.py", line 35, in <module>
kultus-backend |     "user_change_form_url": get_user_change_form_url(person),
kultus-backend |   File "/app/organisations/services.py", line 22, in get_user_change_form_url
kultus-backend |     return domain + reverse("admin:organisations_user_change", args=(person.user_id,))
kultus-backend |   File "/usr/local/lib/python3.9/site-packages/django/urls/base.py", line 54, in reverse
kultus-backend |     app_list = resolver.app_dict[ns]
kultus-backend |   File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 530, in app_dict
kultus-backend |     self._populate()
kultus-backend |   File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 464, in _populate
kultus-backend |     for url_pattern in reversed(self.url_patterns):
kultus-backend |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
kultus-backend |     res = instance.__dict__[self.name] = self.func(instance)
kultus-backend |   File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 602, in url_patterns
kultus-backend |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
kultus-backend |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
kultus-backend |     res = instance.__dict__[self.name] = self.func(instance)
kultus-backend |   File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
kultus-backend |     return import_module(self.urlconf_name)
kultus-backend |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
kultus-backend |     return _bootstrap._gcd_import(name[level:], package, level)
kultus-backend |   File "/app/palvelutarjotin/urls.py", line 12, in <module>
kultus-backend |     admin.site.index_title = " ".join([ugettext("Kultus API"), get_api_version()])
kultus-backend |   File "/app/common/utils.py", line 49, in get_api_version
kultus-backend |     return " | ".join((__version__, settings.REVISION.decode("utf-8")))
kultus-backend | AttributeError: 'str' object has no attribute 'decode'
ERROR: Windows named pipe error: The pipe has been ended. (code: 109)
```
The above happened when I tried to "docker-compose up --build" this PR locally.
setting `REVISION = b"n/a"` instead of `REVISION = "n/a"` in settings.py fixes this for me.

**Comment by terovirtanen** [comment]
> The pipeline is still requiring "Coding style" and "Tests" to be reported: image
> 
> Quite a lot of the SonarCloud Code Analysis seems to do with the snapshots, as they are automatically generated perhaps they could be excluded i.e. all /snapshots/ directories from the SonarCloud Code Analysis? Not necessary to do in this PR IMHO, but an idea how to make things better.

I don't know why Coding style and Tests are still expected, those has removed from GitHub and are run by DevOps as part of Static tests.

SonarCloud issues should be fixed with another PR

**Comment by terovirtanen** [comment]
> ```shell
> kultus-backend |   File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
> kultus-backend |     return import_module(self.urlconf_name)
> kultus-backend |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
> kultus-backend |     return _bootstrap._gcd_import(name[level:], package, level)
> kultus-backend |   File "/app/palvelutarjotin/urls.py", line 12, in <module>
> kultus-backend |     admin.site.index_title = " ".join([ugettext("Kultus API"), get_api_version()])
> kultus-backend |   File "/app/common/utils.py", line 49, in get_api_version
> kultus-backend |     return " | ".join((__version__, settings.REVISION.decode("utf-8")))
> kultus-backend | AttributeError: 'str' object has no attribute 'decode'
> ERROR: Windows named pipe error: The pipe has been ended. (code: 109)
> ```
> 
> The above happened when I tried to "docker-compose up --build" this PR locally. setting `REVISION = b"n/a"` instead of `REVISION = "n/a"` in settings.py fixes this for me.

Docker compose works fine on my local environment e.g. no changes required to the settings.py

**Pull request merged**
