### PR TITLE
PT-1601 | feat: add send_upcoming_occurrence_sms_reminders management command

### PR DESCRIPTION
**Pull request by karisal-anders**
## Description

---
**NOTE**:
 - **Updating** the **snapshot** tests seems to be **flaky** (i.e. inconsistent). Seems "pytest --snapshot-update" + pushing to CI doesn't make snapshot tests pass consistently.
---

### feat: add send_upcoming_occurrence_sms_reminders management command

```
usage: manage.py send_upcoming_occurrence_sms_reminders --days DAYS

Send upcoming occurrences' SMS reminders

mandatory arguments:
  --days DAYS, -d DAYS  Number of days to event's occurrence
```

tests:
 - add test_send_upcoming_occurrence_sms_reminders_command test
 - update snapshots

also:
 - add some syntactic sugar helpers to NotificationService
 - make email/SMS sending both optional in
   send_event_notifications_to_contact_people and use the optionality
   to only send SMSs in send_upcoming_occurrence_sms_reminders
 - add boolean return value for success/failure to send_sms_notification

refs PT-1601

## Tickets

[PT-1601](https://helsinkisolutionoffice.atlassian.net/browse/PT-1601)

[PT-1601]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**KULTUS-API branch is deployed to platta: https://kultus-pr328.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KULTUS-API branch is deployed to platta: https://kultus-pr328.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KULTUS-API branch is deployed to platta: https://kultus-pr328.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KULTUS-API branch is deployed to platta: https://kultus-pr328.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KULTUS-API branch is deployed to platta: https://kultus-pr328.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by karisal-anders** [comment]
Have been running "pytest --snapshot-update" a few times and getting different results and pushing them to CI and seeing if they pass. None have passed so far.

**Comment by terovirtanen** [comment]
**KULTUS-API branch is deployed to platta: https://kultus-pr328.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — APPROVED** [review]
LGTM. Just a note that I didn't test this any how (at least yet).

**Pull request merged**
