### PR TITLE
PT-1730 | Update Python 3.9→3.11, Django 3.2→4.2, Postgres 10→13 and all dependencies, use ruff

### PR DESCRIPTION
**Pull request by karisal-anders**
## Description

- Upgrade
  - Python 3.9 → 3.11
  - Django 3.2 → 4.2
  - Postgres 10 → 13
  - All dependencies
- Use ruff instead of black/isort/flake8 for formatting & linting
- Migrate from `setup.cfg` to `pyproject.toml`
- Remove all warnings from all tests

**Requires** DevOps **pipeline changes**:
 - [PT-1730 | Upgrade Python 3.8 -> 3.11](https://dev.azure.com/City-of-Helsinki/kultus/_git/kultus-pipelines/pullrequest/9694) (Merged)
 - [PT-1730 | Upgrade PostgreSQL 11 -> 13](https://dev.azure.com/City-of-Helsinki/kultus/_git/kultus-pipelines/pullrequest/9695) (Merged)
 - [Use ruff instead of black/isort/flake8 for formatting & linting](https://dev.azure.com/City-of-Helsinki/kultus/_git/kultus-pipelines/pullrequest/9696) (Merged)

## Related

[PT-1730](https://helsinkisolutionoffice.atlassian.net/browse/PT-1730)

[PT-1730]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Graphene 3 changed from using enum values to enums, for example:
```python
class TestEnum(graphene.Enum):
  FIRST = 'first'
  SECOND = 'second'
```
would've been serialized previously using the enum values, i.e.
'first' and 'second'. But with Graphene 3 they are serialized as
'TestEnum.FIRST' and 'TestEnum.SECOND'. This broke functionality as
parts of the codebase were expecting the enum values as per Graphene 2.

Forced backwards compatibility by forcefully mapping enums to their
values.

Related https://github.com/graphql-python/graphene issues & PRs:
 - "Improve enum compatibility" PR:
   - https://github.com/graphql-python/graphene/pull/1153
 - "graphene3: enum doesn't resolve to value" issue:
   - https://github.com/graphql-python/graphene/issues/1277
 - "I would like my enum input values to be the enum instance instead
   of the enum values" issue:
   - https://github.com/graphql-python/graphene/issues/1151

See https://github.com/graphql-python/graphene/wiki/v3-release-notes
for Graphene v3's breaking changes,

[KK-1108]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

## Manual testing

- check out branch
- `cp docker-compose.env.yaml.example docker-compose.env.yaml`
- `docker compose down --remove-orphans`
- `docker compose up --build`
- `docker exec -it kultus-backend bash`
  - `pytest . -vv`
    - Avot! All tests passed when run locally in Docker

### CODE REVIEW

**Comment by terovirtanen** [comment]
**KULTUS-API branch is deployed to platta: https://kultus-pr364.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KULTUS-API branch is deployed to platta: https://kultus-pr364.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KULTUS-API branch is deployed to platta: https://kultus-pr364.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KULTUS-API branch is deployed to platta: https://kultus-pr364.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KULTUS-API branch is deployed to platta: https://kultus-pr364.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KULTUS-API branch is deployed to platta: https://kultus-pr364.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KULTUS-API branch is deployed to platta: https://kultus-pr364.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KULTUS-API branch is deployed to platta: https://kultus-pr364.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KULTUS-API branch is deployed to platta: https://kultus-pr364.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by karisal-anders** [comment]
[Force pushed](https://github.com/City-of-Helsinki/palvelutarjotin/compare/8c451cc658067c64a79e07f7ab61e20ffed38aee..ced136c79f078ddd78363dcf92b4a97652571e59) adding back `field = "__all__"` to EnrolmentReportAdminForm, removing it was not necessary and upgrading all dependencies to latest.

**Comment by karisal-anders** [comment]
@nikomakela @melniiv @jakezu Anyone code reviewing this please take into account that this won't pass currently in CI/CD pipeline because the CI/CD pipelines would need to be updated related to Python version, PostgreSQL version and black/isort/flake8→ruff change in order for everything to pass in CI/CD pipeline.

**Comment by terovirtanen** [comment]
**KULTUS-API branch is deployed to platta: https://kultus-pr364.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — COMMENTED** [review]
I checked all the code changes, but I haven't tested them yet, at all. In Kukkuu API there were some issues in graphql introspection query (publicity), etc. Those could be tested before merging the changes to test env.

**Comment by terovirtanen** [comment]
**KULTUS-API branch is deployed to platta: https://kultus-pr364.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KULTUS-API branch is deployed to platta: https://kultus-pr364.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by karisal-anders** [comment]
Fixed one problem found when using /graphql endpoint locally in 0522622b533f86d2ddde4272c49e187d91f03b42.

Updated DevOps pipelines to use Python 3.11, PostgreSQL 13 and ruff -> Now the pipelines work.

**Comment by karisal-anders** [comment]
Looks like there's still something broken, using the branch locally and trying to query /graphql using GraphiQL raises errors:
image

**Comment by karisal-anders** [comment]
> Looks like there's still something broken, using the branch locally and trying to query /graphql using GraphiQL raises errors: image

False alarm, used a wrong query. Querying with `popularKultusKeywords` works now ✅:
```graphql
fragment localisedFields on LocalisedObject {
  en
  fi
  sv
}

fragment keywordFields on Keyword {
  id
  internalId
  name {
    ...localisedFields
  }
}

query PopularKeywords($amount: Int, $showAllKeywords: Boolean) {
  popularKultusKeywords(amount: $amount, showAllKeywords: $showAllKeywords) {
    meta {
      count
      next
      previous
    }
    data {
      ...keywordFields
    }
  }
}
```

Querying the above using this branch's code running locally in docker:
image

**Review by nikomakela — APPROVED** [review]

**Pull request merged**
