### PR TITLE
PT-1625 | remove beta status completely as Kultus API is in production use

### PR DESCRIPTION
**Pull request by karisal-anders**
## Description

**NOTE**:
 - **Related** [Kultus Platta PR #3996](https://dev.azure.com/City-of-Helsinki/kultus/_git/kultus-pipelines/pullrequest/3996) has been merged on the Platta side.

### chore: remove beta status completely as Kultus API is in production use 

refs PT-1625 (removing beta status from Kultus API)
refs PT-1569 (setting up palvelutarjotin(|-ui|-admin))
 
### tests: update snapshots by pytest --snapshot-update 

refs PT-1625 (removing beta status from Kultus API)
refs PT-1569 (setting up palvelutarjotin(|-ui|-admin))

## Related

 - [PT-1625](https://helsinkisolutionoffice.atlassian.net/browse/PT-1625)
 - [PT-1569](https://helsinkisolutionoffice.atlassian.net/browse/PT-1569)

[PT-1625]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PT-1569]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**kultus-api branch is deployed to platta: https://kultus-api-pr301.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-api branch is deployed to platta: https://kultus-api-pr301.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — APPROVED** [review]
I kind of thought that these changes were already done when the old Kultus was replaced with this repo. So, I think that this is totally ok, but I don't remember whether there could have been some kind of "we are just beta so we can include bugs" kind of decision, so this could be asked from the Product owner too.

**Comment by terovirtanen** [comment]
**kultus-api branch is deployed to platta: https://kultus-api-pr301.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-api branch is deployed to platta: https://kultus-api-pr301.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-api branch is deployed to platta: https://kultus-api-pr301.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by karisal-anders** [comment]
The ["Build & Review / Review (pull_request)"](https://github.com/City-of-Helsinki/palvelutarjotin/actions/runs/4402359256/jobs/7709447496) failing with
> Upgrading chart from 'bitnami/postgresql': Error: failed to download "bitnami/postgresql" at version "10.16.1"

is a known bug at the moment.

[SonarCloud Code Analysis](https://github.com/City-of-Helsinki/palvelutarjotin/pull/301/checks?check_run_id=11949667616) failed because of code duplication but those code duplications are not caused by this PR so it is ok.

**Pull request merged**
